name: Create System Files For GitHub Release

env:
  project_url: "https://github.com/${{ github.repository }}"
  latest_manifest_url: "https://github.com/${{ github.repository }}/releases/latest/download/system.json"
  release_system_url: "https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/rils-mahjong.zip"

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract Version From Tag
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Modify System Manifest With Release-Specific Values
        id: sub_manifest_link_version
        uses: cschleiden/replace-tokens@v1
        with:
          files: "system.json"
        env:
          VERSION: ${{ steps.get_version.outputs.version-without-v }}
          URL: ${{ env.project_url }}
          MANIFEST: ${{ env.latest_manifest_url }}
          DOWNLOAD: ${{ env.release_system_url }}

      - name: Create System Archive
        run: |
          zip \
            --recurse-paths \
            ./rils-mahjong.zip \
            system.json \
            README.md \
            LICENSE \
            templates \
            styles/ \
            packs/ \
            lang/ \
            RILs-Mahjong.mjs

      - name: Update Release With Files
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: ${{ github.event.release.name }}
          draft: ${{ github.event.release.unpublished }}
          prerelease: ${{ github.event.release.prerelease }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./system.json, ./system.zip"
          tag: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}
